name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
          build-root-directory: triangle
          
#      - name: Build with Gradle
 #       with:
  #        arguments: build jacocoTestReport
   #   - name: Upload JaCoCo coverage report as a workflow artifact
    #    uses: actions/upload-artifact@v3.1.1
     #   with:
      #    name: jacoco-report
       #   path: Piazza-Panic-Assessment2/tests/src/io/tests/
      
      
